### PR TITLE
Kh it2 seed stations

### PR DESCRIPTION
**Pull request by kheppenstall**
-Complete iteration 2 by seeding station.csv file into database
-Add all methods to station.rb for dashboard
-Test all methods for station-dashboard

### CODE REVIEW

**Comment by kheppenstall** [comment]
@Daleon @Dpalazzari

**Comment by kheppenstall** [comment]
Note: You need to download the station.csv file on your own and then run rake db:seed to get all the data to load.

Note: Station.count is an active record method but we will be using it on the dashboard

**Comment by kheppenstall** [comment]
This branch is mostly done with iteration three but we still need to
-Create station/dashboard erb file with path /station-dashboard and test it
-Link to the dashboard from the station index page and test it

**Comment by Dpalazzari** [comment]
a little caveat on the Station.rb class...pretty sure you don't have to type Station.where or Station.average for Active record methods. Should still work if you just do where or average. The methods already have self. on every one of them. It'll work.

**Comment by kheppenstall** [comment]
@Dpalazzari Nice Catch. I'll change those methods now and update the pull request.

**Comment by kheppenstall** [comment]
@Dpalazzari @Daleon Finished up the erb file and ready to merge!

**Pull request merged**
